### ISSUE TITLE
ImportError: Numba needs NumPy 1.22 or greater. Got NumPy 1.21.

### ISSUE THREAD

**Issue by roc138** [shepherdpp/qteasy#136]
运行代码
import qteasy as qt

# 下载股票数据 (从2023年1月1日到2023年12月31日之间的所有股票数据)
qt.refill_data_source(tables='stock_daily', start_date='20240101', end_date='20240402')

报错

C:\ProgramData\anaconda3\envs\python38\python.exe C:\Users\Administrator\PycharmProjects\qteasy-1\qteasy-data-t2.py 
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\qteasy-1\qteasy-data-t2.py", line 1, in <module>
    import qteasy as qt
  File "C:\ProgramData\anaconda3\envs\python38\lib\site-packages\qteasy\__init__.py", line 23, in <module>
    import qteasy.utilfuncs
  File "C:\ProgramData\anaconda3\envs\python38\lib\site-packages\qteasy\utilfuncs.py", line 19, in <module>
    from numba import njit
  File "C:\ProgramData\anaconda3\envs\python38\lib\site-packages\numba\__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "C:\ProgramData\anaconda3\envs\python38\lib\site-packages\numba\__init__.py", line 40, in _ensure_critical_deps
    raise ImportError(msg)
ImportError: Numba needs NumPy 1.22 or greater. Got NumPy 1.21.

进程已结束，退出代码为 1

**Comment by roc138** [comment]
经过搜索，发现了博客园中的方法
https://www.cnblogs.com/qteasy/p/18064894
qt.refill_data_source(tables='trade_calendar, stock_basic, index_basic')

还是有些报错，可能windows问题，我试试linux吧

**Comment by roc138** [comment]
1.17 版本解决问题了，用起来顺了，太爽了。

**Comment by shepherdpp** [comment]
之前版本的qteasy一直在python3.8环境中开发，`pandas`、`numpy`和`numba`的版本都相对较低，高版本的numba、numpy调整了一些功能，导致运行会报错。
对此从1.1.7版本开始，我特别注意了`qteasy`对高版本的`python`以及最新版本`numba/numpy`的兼容性。目前在`python`3.12及以下版本中都可以安装及运行。更多的兼容性测试也正在python3.7～3.12的所有版本上同时运行，如果发现还有兼容性问题也会在后续的patch中修复，敬请期待！

**Comment by shepherdpp** [comment]
从v1.1.7开始，以后版本的qteasy都经测试能在python3.7一直到3.12的环境中运行，如果您遇到同样的问题，请升级qteasy到最新版本：
```
$ pip intall tushare -U
```

本问题已解决，我将关闭此Issue
