### ISSUE TITLE
下载tushare上的期货主力与连续合约接口报错 some items in tables list are not valid: ['fut_mapping']

### ISSUE THREAD

**Issue by roc138** [shepherdpp/qteasy#171]
我想下载tushare上的期货主力与连续合约，但报错，有些其他表是可以下载的，也有很多接口都报类似错误，请问大神需要怎么处理？

接口：fut_mapping

<img width="666" alt="8111" src="https://github.com/user-attachments/assets/18d7d542-cb87-480d-bce8-7d43a5a2fe39">

代码：
qt.refill_data_source(
        tables=['fut_mapping'],      
)

报错：
C:\ProgramData\anaconda3\envs\qteasy-env-p311\python.exe I:\qteasy\qteasy-t3\t1-future.py 
Traceback (most recent call last):
  File "I:\qteasy\qteasy-t3\t1-future.py", line 6, in <module>
    qt.refill_data_source(
  File "C:\ProgramData\anaconda3\envs\qteasy-env-p311\Lib\site-packages\qteasy\core.py", line 712, in refill_data_source
    data_source.refill_local_source(
  File "C:\ProgramData\anaconda3\envs\qteasy-env-p311\Lib\site-packages\qteasy\database.py", line 4907, in refill_local_source
    raise KeyError(f'some items in tables list are not valid: '
**KeyError: "some items in tables list are not valid: ['fut_mapping']"**
Filling data source db:mysql://localhost@3306/qt_db ...

**Comment by shepherdpp** [comment]
`tushare` 在不断更新增加新的数据表，但是在`qteasy`中尚未增加相应的数据表与之对应，因此会触发这个错误。
关于新增的数据表，需要在`database.py`中定义它的`SCHEMA`，数据类型等信息，然后就可以下载了。
这是一个比较简单的升级，在未来的更新中会增加

**Comment by shepherdpp** [comment]
关于`fut_mapping`表的问题，现在已经解决。
请升级到`qteasy` `v1.4.0`以后的版本
在新版本中已经增加了更多的`DataSource`数据表，其中就包括`fut_mapping`表，可以使用：
```python
import qteasy as qt
qt.refill_data_source(tables='future_mapping', channel='tushare', data_source=qt.QT_DATA_SOURCE)
```
`v1.4`版本的`qteasy`提供了大量关于数据表、数据类型和数据获取渠道的升级，关于更多数据表和数据类型的信息，请查看持续更新中的`qteasy`文档
