### ISSUE TITLE
新手实在运行不起来，请教牛人

### ISSUE THREAD

**Issue by ziarcher** [shepherdpp/qteasy#92]
Python 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)] on win32
>>> import qteasy as qt
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.3.1\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2023.3.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuewe\Documents\GitHub\qteasy-master\.venv\Lib\site-packages\qteasy\__init__.py", line 22, in <module>
    from .core import run, set_config, get_configurations, get_config
  File "C:\Program Files\JetBrains\PyCharm 2023.3.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuewe\Documents\GitHub\qteasy-master\.venv\Lib\site-packages\qteasy\core.py", line 23, in <module>
    from .history import get_history_panel, HistoryPanel, stack_dataframes
  File "C:\Program Files\JetBrains\PyCharm 2023.3.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuewe\Documents\GitHub\qteasy-master\.venv\Lib\site-packages\qteasy\history.py", line 20, in <module>
    class HistoryPanel():
  File "C:\Users\yuewe\Documents\GitHub\qteasy-master\.venv\Lib\site-packages\qteasy\history.py", line 636, in HistoryPanel
    def fillna(self, with_val: [int, float, int, np.float]):
                                                 ^^^^^^^^
  File "C:\Users\yuewe\Documents\GitHub\qteasy-master\.venv\Lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

**Comment by shepherdpp** [comment]
谢谢您报告此问题，这是个`numpy`的版本兼容性问题。请检查您使用的`numpy`的版本：
```
>>> import numpy as np
>>> np.__version__
```
最新的`numpy`版本已经去掉了一些数据类型的支持，我会在下个发行版本中修复此问题。
现在您要继续使用qteasy，可以强制安装1.21.5版本的`numpy`：
```
$ pip install --force-reinstall numpy==1.21.5
```
安装好之后仍然会有`DeprecationWarning`，但是运行不会有问题

**Comment by ziarcher** [comment]
大佬居然回复了， 太感谢了！(*^▽^*)

**Comment by shepherdpp** [comment]
您客气了！
这几天正在着手检查版本兼容性的问题，建议在一个独立的环境中安装qteasy。另外，修正问题的同时，我也会更新使用教程，力图更加清晰易懂
